title: Many-task pipelines
description: Split-apply-combine paradigm and our USGS Data Science Branch implementations
template:
  name: ds-pipelines-3-template
  repo: ds-pipelines-3
before:
  - type: createIssue
    title: Recognize the unique demands of big collaborative pipelines
    body: 00-overview.md
    store:
      overview_issue_url: '{{ result.data.html_url }}'
steps:
  - title: Get the big picture
    description: Recognize the unique demands of big collaborative pipelines
    link: '{{ store.overview_issue_url }}'
    event: issues.assigned
    actions:
      - type: respond
        with: 01-access-caches.md
        store:
          install_activity_url: '{{ result.data.html_url }}'
